# Generated by Django 5.2.4 on 2025-07-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo_primario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemons_primarios', to='core.tipo', verbose_name='Tipo Primário')),
                ('tipo_secundario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokemons_secundarios', to='core.tipo', verbose_name='Tipo Secundário')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemons',
                'ordering': ['codigo'],
            },
        ),
    ]
